1  move wiki to assets repo
teamtaverna/taverna pull request #2
Opened 2016-10-11 09:37 UTC by andela-kanyanwu

#1 

Update readme with workflow from core repo
Add PR convention from core repo

2016-10-11 09:37 UTC, andela-kanyanwu commented
@andela-uawili @andela-cobiora Please help review above PR.

2016-10-12 09:09 UTC, nbyodai approved these changes

2016-10-12 15:56 UTC, uzoawili requested changes
With regards to our discussion around this, we agreed it's best to put this in the wiki for the assets repo (which will now be renamed to `taverna`)

2016-11-04 12:18 UTC, andela-kanyanwu commented
@andela-uawili @andela-cobiora we would not need this PR anymore.

2016-11-04 12:18 UTC, closed without merging